# Generated by Django 2.1.5 on 2019-02-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128, unique=True)),
                ('Nationality', models.CharField(max_length=128)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Wallet', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
